const ADD="ADD"
const REDUCE="REDUCE"

const GET_TODO_REQ='GET_TODO_REQ'
const GET_TODO_SUCC='GET_TODO_SUCC'
const GET_TODO_FAILURE='GET_TODO_FAIL'
const UPDATE_TODO='UPDATE_TODO'

const ADD_TODO='ADD_TODO'

export{ADD,REDUCE,GET_TODO_FAILURE,GET_TODO_REQ,GET_TODO_SUCC,UPDATE_TODO,ADD_TODO}